import '@storybook/addon-links/register'
import '@storybook/addon-knobs/register'
import 'storybook-addon-jsx/register'
import '@storybook/addon-viewport/register'
import '@whitespace/storybook-addon-html/register'
